# Generated by Django 3.2 on 2022-10-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0002_solicitudcompra_cantidad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='EstadoSolicitudCompra',
            field=models.CharField(choices=[('1', 'Aguacate '), ('2', 'Damasco'), ('3', 'Piña'), ('4', 'Arándano'), ('5', 'Plátano'), ('6', 'Cereza'), ('7', 'Ciruela'), ('8', 'Coco'), ('9', 'Durazno'), ('10', 'Frambuesa'), ('11', 'Frutilla '), ('12', 'Granada'), ('13', 'Limón'), ('14', 'Mandarina'), ('15', 'Melón'), ('16', 'Sandia '), ('17', 'Membrillo'), ('18', 'Mora'), ('19', 'Pera'), ('20', 'Manzana'), ('21', 'Naranja')], default='3', max_length=50, null=True),
        ),
    ]
