# Generated by Django 3.2 on 2022-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0003_solicitudcompra_estadosolicitudcompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='EstadoSolicitudCompra',
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='EstadoSolicitud',
            field=models.CharField(choices=[('1', 'aprobado'), ('2', 'rechazado'), ('3', 'Pendiente'), ('4', 'Completado'), ('5', 'Devuelto'), ('6', 'Subasta'), ('7', 'En camino')], default='3', max_length=50, null=True),
        ),
    ]
