# Generated by Django 3.1.2 on 2021-07-04 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0005_post_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='feriavirtualapp.post'),
            preserve_default=False,
        ),
    ]
