# Generated by Django 4.1 on 2022-09-30 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0008_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(choices=[('1', 'Ligero '), ('2', 'Liviano'), ('3', 'Semi Liviano'), ('4', 'Mediano'), ('5', 'Semi esado'), ('6', 'Pesado'), ('7', 'Extra Pesado'), ('8', 'Mega Pesado'), ('9', 'Ultra Pesado'), ('10', 'Extra Pesado'), ('11', 'Giga Pesado'), ('12', 'Super Pesado')], max_length=50, null=True)),
                ('refrigeracion', models.BooleanField(default=False)),
                ('fruta', models.CharField(choices=[('1', 'Aguacate '), ('2', 'Damasco'), ('3', 'Piña'), ('4', 'Arándano'), ('5', 'Plátano'), ('6', 'Cereza'), ('7', 'Ciruela'), ('8', 'Coco'), ('9', 'Durazno'), ('10', 'Frambuesa'), ('11', 'Frutilla '), ('12', 'Granada'), ('13', 'Limón'), ('14', 'Mandarina'), ('15', 'Melón'), ('16', 'Sandia '), ('17', 'Membrillo'), ('18', 'Mora'), ('19', 'Pera'), ('20', 'Manzana'), ('21', 'Naranja')], max_length=50, null=True)),
                ('variedad', models.CharField(max_length=50, null=True)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='Posts')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClienteT', to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductorT', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postTransporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
