# Generated by Django 4.1 on 2022-09-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0009_posttransporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttransporte',
            old_name='user',
            new_name='transportista',
        ),
    ]
