# Generated by Django 4.1 on 2022-10-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0004_auto_20221004_2010'),
        ('feriavirtualapp', '0010_rename_user_posttransporte_transportista'),
    ]

    operations = [
    ]
