# Generated by Django 4.1 on 2022-10-09 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0012_merge_20221009_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('1', 'aprobado'), ('2', 'rechazado'), ('3', 'Pendiente'), ('4', 'Completado'), ('5', 'Devuelto'), ('6', 'Subasta'), ('7', 'En camino')], default='3', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='EstadoSolicitud',
            field=models.CharField(choices=[('1', 'aprobado'), ('2', 'rechazado'), ('3', 'Pendiente'), ('4', 'Completado'), ('5', 'Devuelto'), ('6', 'Subasta'), ('7', 'En camino')], default='3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClienteSoli', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
    ]
