# Generated by Django 4.1 on 2022-09-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0006_notificacion_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('1', 'Productor'), ('2', 'Cliente externo'), ('3', 'Cliente interno'), ('4', 'Transportista'), ('5', 'Consultor'), ('6', 'Administrador'), ('6', 'Revisor de calidad')], max_length=50, null=True),
        ),
    ]
