# Generated by Django 4.1 on 2022-10-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0011_merge_20221005_2302'),
        ('feriavirtualapp', '0011_merge_20221005_2303'),
    ]

    operations = [
    ]
