# Generated by Django 4.1 on 2022-10-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0013_estadopr_remove_post_user_post_estadosolicitud_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoPr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fruta',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fruta',
            new_name='producto',
        ),
    ]
