# Generated by Django 4.1 on 2022-10-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0015_remove_posttransporte_fruta_post_calibre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relacion',
            new_name='ProcesoVenta',
        ),
        migrations.RenameIndex(
            model_name='procesoventa',
            new_name='feriavirtua_from_po_0e19e5_idx',
            old_name='feriavirtua_from_po_353ef8_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='calibre',
            field=models.CharField(choices=[('1', 'Segunda'), ('2', 'Primera'), ('3', 'Extra ')], default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='calibre',
            field=models.CharField(choices=[('1', 'Segunda'), ('2', 'Primera'), ('3', 'Extra ')], max_length=50, null=True),
        ),
    ]
