# Generated by Django 4.1 on 2022-10-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualapp', '0016_rename_relacion_procesoventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='EstadoSolicitud',
            field=models.CharField(choices=[('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Pendiente'), ('4', 'Subasta Transporte'), ('5', 'Esperando productos en bodega central'), ('6', 'Revision de calidad'), ('7', 'En camino'), ('8', 'Destino')], default='3', max_length=50, null=True),
        ),
    ]
